{
    "Modified": "2010-08-21T01:19:02.370000",
    "Published": "2008-04-22T00:41:00",
    "access": {
        "authentication": "NONE",
        "complexity": "MEDIUM",
        "vector": "NETWORK"
    },
    "capec": [],
    "cvss": "6.8",
    "cvss-time": "2008-04-22T09:11:00",
    "cwe": "CWE-189",
    "id": "CVE-2008-1679",
    "impact": {
        "availability": "PARTIAL",
        "confidentiality": "PARTIAL",
        "integrity": "PARTIAL"
    },
    "last-modified": "2017-09-28T21:30:49.317000",
    "nessus": [
        {
            "NASL family": "MacOS X Local Security Checks",
            "NASL id": "MACOSX_SECUPD2009-001.NASL",
            "description": "The remote host is running a version of Mac OS X 10.5 or 10.4 that does not have Security Update 2009-001 applied.\n\nThis security update contains fixes for the following products :\n\n  - AFP Server\n  - Apple Pixlet Video\n  - CarbonCore\n  - CFNetwork\n  - Certificate Assistant\n  - ClamAV\n  - CoreText\n  - CUPS\n  - DS Tools\n  - fetchmail\n  - Folder Manager\n  - FSEvents\n  - Network Time\n  - perl\n  - Printing\n  - python\n  - Remote Apple Events\n  - Safari RSS\n  - servermgrd\n  - SMB\n  - SquirrelMail\n  - X11\n  - XTerm",
            "last seen": "2019-02-21",
            "modified": "2018-07-16",
            "plugin id": "35684",
            "published": "2009-02-13",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=35684",
            "title": "Mac OS X Multiple Vulnerabilities (Security Update 2009-001)"
        },
        {
            "NASL family": "Gentoo Local Security Checks",
            "NASL id": "GENTOO_GLSA-200807-01.NASL",
            "description": "The remote host is affected by the vulnerability described in GLSA-200807-01 (Python: Multiple integer overflows)\n\n    Multiple vulnerabilities were discovered in Python:\n    David     Remahl reported multiple integer overflows in the file imageop.c,     leading to a heap-based buffer overflow (CVE-2008-1679). This issue is     due to an incomplete fix for CVE-2007-4965.\n    Justin Ferguson     discovered that an integer signedness error in the zlib extension     module might trigger insufficient memory allocation and a buffer     overflow via a negative signed integer (CVE-2008-1721).\n    Justin     Ferguson discovered that insufficient input validation in the     PyString_FromStringAndSize() function might lead to a buffer overflow     (CVE-2008-1887).\n  Impact :\n\n    A remote attacker could exploit these vulnerabilities to cause a Denial     of Service or possibly the remote execution of arbitrary code with the     privileges of the user running Python.\n  Workaround :\n\n    There is no known workaround at this time.",
            "last seen": "2019-02-21",
            "modified": "2018-07-11",
            "plugin id": "33421",
            "published": "2008-07-08",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33421",
            "title": "GLSA-200807-01 : Python: Multiple integer overflows"
        },
        {
            "NASL family": "Debian Local Security Checks",
            "NASL id": "DEBIAN_DSA-1620.NASL",
            "description": "Several vulnerabilities have been discovered in the interpreter for the Python language. The Common Vulnerabilities and Exposures project identifies the following problems :\n\n  - CVE-2007-2052     Piotr Engelking discovered that the strxfrm() function     of the locale module miscalculates the length of an     internal buffer, which may result in a minor information     disclosure.\n\n  - CVE-2007-4965     It was discovered that several integer overflows in the     imageop module may lead to the execution of arbitrary     code, if a user is tricked into processing malformed     images. This issue is also tracked as CVE-2008-1679 due     to an initially incomplete patch.\n\n  - CVE-2008-1721     Justin Ferguson discovered that a buffer overflow in the     zlib module may lead to the execution of arbitrary code.\n\n  - CVE-2008-1887     Justin Ferguson discovered that insufficient input     validation in PyString_FromStringAndSize() may lead to     the execution of arbitrary code.",
            "last seen": "2019-02-21",
            "modified": "2018-11-10",
            "plugin id": "33740",
            "published": "2008-07-28",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33740",
            "title": "Debian DSA-1620-1 : python2.5 - several vulnerabilities"
        },
        {
            "NASL family": "Slackware Local Security Checks",
            "NASL id": "SLACKWARE_SSA_2008-217-01.NASL",
            "description": "New python packages are available for Slackware 10.1, 10.2, 11.0, 12.0, 12.1, and -current to fix security issues.",
            "last seen": "2019-02-21",
            "modified": "2018-06-27",
            "plugin id": "33824",
            "published": "2008-08-05",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33824",
            "title": "Slackware 10.1 / 10.2 / 11.0 / 12.0 / 12.1 / current : python (SSA:2008-217-01)"
        },
        {
            "NASL family": "Mandriva Local Security Checks",
            "NASL id": "MANDRIVA_MDVSA-2008-163.NASL",
            "description": "Multiple integer overflows in the imageop module in Python prior to 2.5.3 allowed context-dependent attackers to cause a denial of service (crash) or possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows (CVE-2008-1679). This was due to an incomplete fix for CVE-2007-4965.\n\nDavid Remahl of Apple Product Security reported several integer overflows in a number of core modules (CVE-2008-2315). He also reported an integer overflow in the hashlib module on Python 2.5 that lead to unreliable cryptographic digest results (CVE-2008-2316).\n\nJustin Ferguson reported multiple buffer overflows in unicode string processing that affected 32bit systems (CVE-2008-3142).\n\nMultiple integer overflows were reported by the Google Security Team that had been fixed in Python 2.5.2 (CVE-2008-3143).\n\nJustin Ferguson reported a number of integer overflows and underflows in the PyOS_vsnprintf() function, as well as an off-by-one error when passing zero-length strings, that led to memory corruption (CVE-2008-3144).\n\nThe updated packages have been patched to correct these issues. As well, Python packages on Mandriva Linux 2007.1 and 2008.0 have been updated to version 2.5.2. Due to slight packaging changes on Mandriva Linux 2007.1, a new package is available (tkinter-apps) that contains binary files (such as /usr/bin/idle) that were previously in the tkinter package.",
            "last seen": "2019-02-21",
            "modified": "2018-07-19",
            "plugin id": "37212",
            "published": "2009-04-23",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=37212",
            "title": "Mandriva Linux Security Advisory : python (MDVSA-2008:163)"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "SUSE_PYTHON-5490.NASL",
            "description": "This update of python fixes several security vulnerabilities.\n(CVE-2008-1679 / CVE-2008-1887 / CVE-2008-3143 / CVE-2008-3142 / CVE-2008-3144 / CVE-2008-2315 / CVE-2008-2316) Note: for SLE10 a non-security bug in mmap was fixed too.",
            "last seen": "2019-02-21",
            "modified": "2016-12-22",
            "plugin id": "33923",
            "published": "2008-08-17",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33923",
            "title": "SuSE 10 Security Update : Python (ZYPP Patch Number 5490)"
        },
        {
            "NASL family": "Oracle Linux Local Security Checks",
            "NASL id": "ORACLELINUX_ELSA-2009-1177.NASL",
            "description": "From Red Hat Security Advisory 2009:1177 :\n\nUpdated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 4.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nAn integer signedness error, leading to a buffer overflow, was found in the Python zlib extension module. If a Python application requested the negative byte count be flushed for a decompression stream, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges.\n(CVE-2008-1721)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-07-18",
            "plugin id": "67897",
            "published": "2013-07-12",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=67897",
            "title": "Oracle Linux 4 : python (ELSA-2009-1177)"
        },
        {
            "NASL family": "Debian Local Security Checks",
            "NASL id": "DEBIAN_DSA-1551.NASL",
            "description": "Several vulnerabilities have been discovered in the interpreter for the Python language. The Common Vulnerabilities and Exposures project identifies the following problems :\n\n  - CVE-2007-2052     Piotr Engelking discovered that the strxfrm() function     of the locale module miscalculates the length of an     internal buffer, which may result in a minor information     disclosure.\n\n  - CVE-2007-4965     It was discovered that several integer overflows in the     imageop module may lead to the execution of arbitrary     code, if a user is tricked into processing malformed     images. This issue is also tracked as CVE-2008-1679 due     to an initially incomplete patch.\n\n  - CVE-2008-1721     Justin Ferguson discovered that a buffer overflow in the     zlib module may lead to the execution of arbitrary code.\n\n  - CVE-2008-1887     Justin Ferguson discovered that insufficient input     validation in PyString_FromStringAndSize() may lead to     the execution of arbitrary code.",
            "last seen": "2019-02-21",
            "modified": "2018-11-10",
            "plugin id": "32006",
            "published": "2008-04-22",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=32006",
            "title": "Debian DSA-1551-1 : python2.4 - several vulnerabilities"
        },
        {
            "NASL family": "Red Hat Local Security Checks",
            "NASL id": "REDHAT-RHSA-2009-1178.NASL",
            "description": "Updated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 3.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-11-27",
            "plugin id": "40402",
            "published": "2009-07-28",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=40402",
            "title": "RHEL 3 : python (RHSA-2009:1178)"
        },
        {
            "NASL family": "CentOS Local Security Checks",
            "NASL id": "CENTOS_RHSA-2009-1178.NASL",
            "description": "Updated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 3.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-11-10",
            "plugin id": "40394",
            "published": "2009-07-28",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=40394",
            "title": "CentOS 3 : python (CESA-2009:1178)"
        },
        {
            "NASL family": "Ubuntu Local Security Checks",
            "NASL id": "UBUNTU_USN-632-1.NASL",
            "description": "It was discovered that there were new integer overflows in the imageop module. If an attacker were able to trick a Python application into processing a specially crafted image, they could execute arbitrary code with user privileges. (CVE-2008-1679)\n\nJustin Ferguson discovered that the zlib module did not correctly handle certain archives. If an attacker were able to trick a Python application into processing a specially crafted archive file, they could execute arbitrary code with user privileges. (CVE-2008-1721)\n\nJustin Ferguson discovered that certain string manipulations in Python could be made to overflow. If an attacker were able to pass a specially crafted string through the PyString_FromStringAndSize function, they could execute arbitrary code with user privileges.\n(CVE-2008-1887)\n\nMultiple integer overflows were discovered in Python's core and modules including hashlib, binascii, pickle, md5, stringobject, unicodeobject, bufferobject, longobject, tupleobject, stropmodule, gcmodule, and mmapmodule. If an attacker were able to exploit these flaws they could execute arbitrary code with user privileges or cause Python applications to crash, leading to a denial of service.\n(CVE-2008-2315, CVE-2008-2316, CVE-2008-3142, CVE-2008-3143, CVE-2008-3144).\n\nNote that Tenable Network Security has extracted the preceding description block directly from the Ubuntu security advisory. Tenable has attempted to automatically clean and format it as much as possible without introducing additional issues.",
            "last seen": "2019-02-21",
            "modified": "2018-11-28",
            "plugin id": "33807",
            "published": "2008-08-04",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33807",
            "title": "Ubuntu 6.06 LTS / 7.04 / 7.10 / 8.04 LTS : python2.4, python2.5 vulnerabilities (USN-632-1)"
        },
        {
            "NASL family": "Scientific Linux Local Security Checks",
            "NASL id": "SL_20090728_PYTHON_FOR_SL_3_0_X.NASL",
            "description": "When the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nWould like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.",
            "last seen": "2019-02-21",
            "modified": "2019-01-02",
            "plugin id": "60624",
            "published": "2012-08-01",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=60624",
            "title": "Scientific Linux Security Update : python for SL 3.0.x on i386/x86_64"
        },
        {
            "NASL family": "Red Hat Local Security Checks",
            "NASL id": "REDHAT-RHSA-2009-1177.NASL",
            "description": "Updated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 4.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nAn integer signedness error, leading to a buffer overflow, was found in the Python zlib extension module. If a Python application requested the negative byte count be flushed for a decompression stream, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges.\n(CVE-2008-1721)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-11-27",
            "plugin id": "40401",
            "published": "2009-07-28",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=40401",
            "title": "RHEL 4 : python (RHSA-2009:1177)"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "SUSE_11_0_PYTHON-080801.NASL",
            "description": "This update of python fixes several security vulnerabilities.\n(CVE-2008-1679,CVE-2008-1887, CVE-2008-3143, CVE-2008-3142, CVE-2008-3144, CVE-2008-2315, CVE-2008-2316)",
            "last seen": "2019-02-21",
            "modified": "2016-12-21",
            "plugin id": "40115",
            "published": "2009-07-21",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=40115",
            "title": "openSUSE Security Update : python (python-128)"
        },
        {
            "NASL family": "Oracle Linux Local Security Checks",
            "NASL id": "ORACLELINUX_ELSA-2009-1178.NASL",
            "description": "From Red Hat Security Advisory 2009:1178 :\n\nUpdated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 3.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-07-18",
            "plugin id": "67898",
            "published": "2013-07-12",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=67898",
            "title": "Oracle Linux 3 : python (ELSA-2009-1178)"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "SUSE_PYTHON-5491.NASL",
            "description": "This update of python fixes several security vulnerabilities.\n(CVE-2008-1679,CVE-2008-1887, CVE-2008-3143, CVE-2008-3142, CVE-2008-3144, CVE-2008-2315, CVE-2008-2316)",
            "last seen": "2019-02-21",
            "modified": "2016-12-22",
            "plugin id": "33924",
            "published": "2008-08-17",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33924",
            "title": "openSUSE 10 Security Update : python (python-5491)"
        },
        {
            "NASL family": "Scientific Linux Local Security Checks",
            "NASL id": "SL_20090728_PYTHON_FOR_SL_4_X.NASL",
            "description": "When the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nAn integer signedness error, leading to a buffer overflow, was found in the Python zlib extension module. If a Python application requested the negative byte count be flushed for a decompression stream, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges.\n(CVE-2008-1721)\n\nWould like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.",
            "last seen": "2019-02-21",
            "modified": "2019-01-02",
            "plugin id": "60625",
            "published": "2012-08-01",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=60625",
            "title": "Scientific Linux Security Update : python for SL 4.x on i386/x86_64"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "SUSE9_12215.NASL",
            "description": "This update of python fixes several security vulnerabilities.\n(CVE-2008-1679 / CVE-2008-1887, CVE-2008-3143, CVE-2008-3142, CVE-2008-3144, CVE-2008-2315, CVE-2008-2316)\n\nNote: for SLE10 a non-security bug in mmap was fixed too.",
            "last seen": "2019-02-21",
            "modified": "2016-12-21",
            "plugin id": "41229",
            "published": "2009-09-24",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=41229",
            "title": "SuSE9 Security Update : Python (YOU Patch Number 12215)"
        }
    ],
    "oval": [
        {
            "accepted": "2013-04-29T04:06:52.162-04:00",
            "class": "vulnerability",
            "contributors": [
                {
                    "name": "Aharon Chernin",
                    "organization": "SCAP.com, LLC"
                },
                {
                    "name": "Dragos Prisaca",
                    "organization": "G2, Inc."
                }
            ],
            "definition_extensions": [
                {
                    "comment": "The operating system installed on the system is Red Hat Enterprise Linux 3",
                    "oval": "oval:org.mitre.oval:def:11782"
                },
                {
                    "comment": "CentOS Linux 3.x",
                    "oval": "oval:org.mitre.oval:def:16651"
                },
                {
                    "comment": "The operating system installed on the system is Red Hat Enterprise Linux 4",
                    "oval": "oval:org.mitre.oval:def:11831"
                },
                {
                    "comment": "CentOS Linux 4.x",
                    "oval": "oval:org.mitre.oval:def:16636"
                },
                {
                    "comment": "Oracle Linux 4.x",
                    "oval": "oval:org.mitre.oval:def:15990"
                }
            ],
            "description": "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965.",
            "family": "unix",
            "id": "oval:org.mitre.oval:def:10583",
            "status": "accepted",
            "submitted": "2010-07-09T03:56:16-04:00",
            "title": "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965.",
            "version": "23"
        },
        {
            "accepted": "2010-03-01T04:00:13.347-05:00",
            "class": "vulnerability",
            "contributors": [
                {
                    "name": "Pai Peng",
                    "organization": "Hewlett-Packard"
                }
            ],
            "definition_extensions": [
                {
                    "comment": "Solaris 10 (SPARC) is installed",
                    "oval": "oval:org.mitre.oval:def:1440"
                },
                {
                    "comment": "Solaris 10 (x86) is installed",
                    "oval": "oval:org.mitre.oval:def:1926"
                }
            ],
            "description": "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965.",
            "family": "unix",
            "id": "oval:org.mitre.oval:def:7800",
            "status": "accepted",
            "submitted": "2010-01-19T17:52:34.000-05:00",
            "title": "Multiple Buffer and Integer Overflow Vulnerabilities in Python (python(1)) May Lead to a Denial of Service (DoS) or Allow Execution of Arbitrary Code",
            "version": "31"
        }
    ],
    "ranking": [
        [
            {
                "circl": 3
            }
        ]
    ],
    "redhat": {
        "rpms": [
            "python-0:2.3.4-14.7.el4_8.2",
            "python-devel-0:2.3.4-14.7.el4_8.2",
            "python-docs-0:2.3.4-14.7.el4_8.2",
            "python-tools-0:2.3.4-14.7.el4_8.2",
            "tkinter-0:2.3.4-14.7.el4_8.2",
            "python-0:2.2.3-6.11",
            "python-devel-0:2.2.3-6.11",
            "python-tools-0:2.2.3-6.11",
            "tkinter-0:2.2.3-6.11"
        ]
    },
    "references": [
        "http://bugs.python.org/issue1179",
        "http://bugs.python.org/msg64682",
        "http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html",
        "http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html",
        "http://security.gentoo.org/glsa/glsa-200807-01.xml",
        "http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289",
        "http://support.apple.com/kb/HT3438",
        "http://support.avaya.com/css/P8/documents/100074697",
        "http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149",
        "http://www.debian.org/security/2008/dsa-1551",
        "http://www.debian.org/security/2008/dsa-1620",
        "http://www.mandriva.com/security/advisories?name=MDVSA-2008:163",
        "http://www.mandriva.com/security/advisories?name=MDVSA-2008:164",
        "http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900",
        "http://www.ubuntu.com/usn/usn-632-1",
        "https://exchange.xforce.ibmcloud.com/vulnerabilities/41958",
        "https://issues.rpath.com/browse/RPL-2424"
    ],
    "refmap": {
        "apple": [
            "APPLE-SA-2009-02-12"
        ],
        "confirm": [
            "http://bugs.python.org/issue1179",
            "http://support.apple.com/kb/HT3438",
            "http://support.avaya.com/css/P8/documents/100074697",
            "http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149",
            "http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900",
            "https://issues.rpath.com/browse/RPL-2424"
        ],
        "debian": [
            "DSA-1551",
            "DSA-1620"
        ],
        "gentoo": [
            "GLSA-200807-01"
        ],
        "mandriva": [
            "MDVSA-2008:163",
            "MDVSA-2008:164"
        ],
        "misc": [
            "http://bugs.python.org/msg64682"
        ],
        "secunia": [
            "29889",
            "29955",
            "30872",
            "31255",
            "31358",
            "31365",
            "31518",
            "31687",
            "33937",
            "38675"
        ],
        "slackware": [
            "SSA:2008-217-01"
        ],
        "suse": [
            "SUSE-SR:2008:017"
        ],
        "ubuntu": [
            "USN-632-1"
        ],
        "xf": [
            "python-imageopc-bo(41958)"
        ]
    },
    "statements": [
        {
            "contributor": "Joshua Bressers",
            "lastmodified": "2008-04-22",
            "organization": "Red Hat",
            "statement": "Red Hat is aware of this issue and is tracking it via the following bug: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=CVE-2008-1679\n\nThe Red Hat Security Response Team has rated this issue as having low security impact, a future update may address this flaw.  More information regarding issue severity can be found here: http://www.redhat.com/security/updates/classification/"
        }
    ],
    "summary": "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.4",
            "title": "cpe:2.3:a:python_software_foundation:python:2.4"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.5.2",
            "title": "cpe:2.3:a:python_software_foundation:python:2.5.2"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [
        "cpe:/a:python_software_foundation:python:2.4",
        "cpe:/a:python_software_foundation:python:2.5.2"
    ]
}