{
    "Modified": "2011-03-07T22:10:16.627000",
    "Published": "2008-08-01T10:41:00",
    "access": {
        "authentication": "NONE",
        "complexity": "LOW",
        "vector": "NETWORK"
    },
    "capec": [],
    "cvss": "5.0",
    "cvss-time": "2008-08-04T09:30:00",
    "cwe": "CWE-189",
    "id": "CVE-2008-3144",
    "impact": {
        "availability": "PARTIAL",
        "confidentiality": "NONE",
        "integrity": "NONE"
    },
    "last-modified": "2018-10-11T16:47:18.770000",
    "nessus": [
        {
            "NASL family": "Debian Local Security Checks",
            "NASL id": "DEBIAN_DSA-1667.NASL",
            "description": "Several vulnerabilities have been discovered in the interpreter for the Python language. The Common Vulnerabilities and Exposures project identifies the following problems :\n\n  - CVE-2008-2315     David Remahl discovered several integer overflows in the     stringobject, unicodeobject, bufferobject, longobject,     tupleobject, stropmodule, gcmodule, and mmapmodule     modules.\n\n  - CVE-2008-3142     Justin Ferguson discovered that incorrect memory     allocation in the unicode_resize() function can lead to     buffer overflows.\n\n  - CVE-2008-3143     Several integer overflows were discovered in various     Python core modules.\n\n  - CVE-2008-3144     Several integer overflows were discovered in the     PyOS_vsnprintf() function.",
            "last seen": "2019-02-21",
            "modified": "2018-11-10",
            "plugin id": "34823",
            "published": "2008-11-21",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=34823",
            "title": "Debian DSA-1667-1 : python2.4 - several vulnerabilities"
        },
        {
            "NASL family": "MacOS X Local Security Checks",
            "NASL id": "MACOSX_SECUPD2009-001.NASL",
            "description": "The remote host is running a version of Mac OS X 10.5 or 10.4 that does not have Security Update 2009-001 applied.\n\nThis security update contains fixes for the following products :\n\n  - AFP Server\n  - Apple Pixlet Video\n  - CarbonCore\n  - CFNetwork\n  - Certificate Assistant\n  - ClamAV\n  - CoreText\n  - CUPS\n  - DS Tools\n  - fetchmail\n  - Folder Manager\n  - FSEvents\n  - Network Time\n  - perl\n  - Printing\n  - python\n  - Remote Apple Events\n  - Safari RSS\n  - servermgrd\n  - SMB\n  - SquirrelMail\n  - X11\n  - XTerm",
            "last seen": "2019-02-21",
            "modified": "2018-07-16",
            "plugin id": "35684",
            "published": "2009-02-13",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=35684",
            "title": "Mac OS X Multiple Vulnerabilities (Security Update 2009-001)"
        },
        {
            "NASL family": "Misc.",
            "NASL id": "VMWARE_VMSA-2009-0016_REMOTE.NASL",
            "description": "The remote VMware ESX / ESXi host is missing a security-related patch.\nIt is, therefore, affected by multiple vulnerabilities, including remote code execution vulnerabilities, in the following components :\n\n  - Apache Geronimo\n  - Apache Tomcat\n  - Apache Xerces2\n  - cURL/libcURL\n  - ISC BIND\n  - Libxml2\n  - Linux kernel\n  - Linux kernel 64-bit\n  - Linux kernel Common Internet File System\n  - Linux kernel eCryptfs\n  - NTP\n  - Python\n  - Java Runtime Environment (JRE)\n  - Java SE Development Kit (JDK)\n  - Java SE Abstract Window Toolkit (AWT)\n  - Java SE Plugin\n  - Java SE Provider\n  - Java SE Swing\n  - Java SE Web Start",
            "last seen": "2019-02-21",
            "modified": "2018-08-06",
            "plugin id": "89117",
            "published": "2016-03-03",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=89117",
            "title": "VMware ESX / ESXi Multiple Vulnerabilities (VMSA-2009-0016) (remote check)"
        },
        {
            "NASL family": "VMware ESX Local Security Checks",
            "NASL id": "VMWARE_VMSA-2009-0016.NASL",
            "description": "a. JRE Security Update\n\n  JRE update to version 1.5.0_20, which addresses multiple security   issues that existed in earlier releases of JRE.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org) has   assigned the following names to the security issues fixed in   JRE 1.5.0_18: CVE-2009-1093, CVE-2009-1094, CVE-2009-1095,   CVE-2009-1096, CVE-2009-1097, CVE-2009-1098, CVE-2009-1099,   CVE-2009-1100, CVE-2009-1101, CVE-2009-1102, CVE-2009-1103,   CVE-2009-1104, CVE-2009-1105, CVE-2009-1106, and CVE-2009-1107.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org) has   assigned the following names to the security issues fixed in   JRE 1.5.0_20: CVE-2009-2625, CVE-2009-2670, CVE-2009-2671,   CVE-2009-2672, CVE-2009-2673, CVE-2009-2675, CVE-2009-2676,   CVE-2009-2716, CVE-2009-2718, CVE-2009-2719, CVE-2009-2720,   CVE-2009-2721, CVE-2009-2722, CVE-2009-2723, CVE-2009-2724.\n\nb. Update Apache Tomcat version\n\n  Update for VirtualCenter and ESX patch update the Tomcat package to   version 6.0.20 (vSphere 4.0) or version 5.5.28 (VirtualCenter 2.5)   which addresses multiple security issues that existed   in the previous version of Apache Tomcat.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org) has   assigned the following names to the security issues fixed in   Apache Tomcat 6.0.20 and Tomcat 5.5.28: CVE-2008-5515,   CVE-2009-0033, CVE-2009-0580, CVE-2009-0781, CVE-2009-0783.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org) has   assigned the following names to the security issues fixed in   Apache Tomcat 6.0.18:  CVE-2008-1232, CVE-2008-1947, CVE-2008-2370.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org) has   assigned the following names to the security issues fixed in   Apache Tomcat 6.0.16:  CVE-2007-5333, CVE-2007-5342, CVE-2007-5461,   CVE-2007-6286, CVE-2008-0002.\n  c. Third-party library update for ntp.\n   The Network Time Protocol (NTP) is used to synchronize a computer's   time with a referenced time source.\n   ESXi 3.5 and ESXi 4.0 have a ntp client that is affected by the   following security issue. Note that the same security issue is   present in the ESX Service Console as described in section d. of   this advisory.\n   A buffer overflow flaw was discovered in the ntpd daemon's NTPv4   authentication code. If ntpd was configured to use public key   cryptography for NTP packet authentication, a remote attacker could   use this flaw to send a specially crafted request packet that could   crash ntpd or, potentially, execute arbitrary code with the   privileges of the 'ntp' user.\n   The Common Vulnerabilities and Exposures Project (cve.mitre.org)   has assigned the name CVE-2009-1252 to this issue.\n   The NTP security issue identified by CVE-2009-0159 is not relevant   for ESXi 3.5 and ESXi 4.0.\n d. Service Console update for ntp\n\n  Service Console package ntp updated to version ntp-4.2.2pl-9el5_3.2    The Network Time Protocol (NTP) is used to synchronize a computer's   time with a referenced time source.\n   The Service Console present in ESX is affected by the following   security issues.\n   A buffer overflow flaw was discovered in the ntpd daemon's NTPv4   authentication code. If ntpd was configured to use public key   cryptography for NTP packet authentication, a remote attacker could   use this flaw to send a specially crafted request packet that could   crash ntpd or, potentially, execute arbitrary code with the   privileges of the 'ntp' user.\n   NTP authentication is not enabled by default on the Service Console.\n   The Common Vulnerabilities and Exposures Project (cve.mitre.org)   has assigned the name CVE-2009-1252 to this issue.\n   A buffer overflow flaw was found in the ntpq diagnostic command. A   malicious, remote server could send a specially crafted reply to an   ntpq request that could crash ntpq or, potentially, execute   arbitrary code with the privileges of the user running the ntpq   command.\n   The Common Vulnerabilities and Exposures Project (cve.mitre.org)   has assigned the name CVE-2009-0159 to this issue.\n  e. Updated Service Console package kernel\n\n  Updated Service Console package kernel addresses the security   issues listed below.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the names CVE-2008-3528, CVE-2008-5700, CVE-2009-0028,   CVE-2009-0269, CVE-2009-0322, CVE-2009-0675, CVE-2009-0676,   CVE-2009-0778 to the security issues fixed in kernel   2.6.18-128.1.6.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the names CVE-2008-4307, CVE-2009-0834, CVE-2009-1337,   CVE-2009-0787, CVE-2009-1336 to the security issues fixed in   kernel 2.6.18-128.1.10.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the names CVE-2009-1439, CVE-2009-1633, CVE-2009-1072,   CVE-2009-1630, CVE-2009-1192 to the security issues fixed in   kernel 2.6.18-128.1.14.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the names CVE-2007-5966, CVE-2009-1385, CVE-2009-1388,   CVE-2009-1389, CVE-2009-1895, CVE-2009-2406, CVE-2009-2407 to the   security issues fixed in kernel 2.6.18-128.4.1.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the names CVE-2009-2692, CVE-2009-2698 to the   security issues fixed in kernel 2.6.18-128.7.1.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the names CVE-2009-0745, CVE-2009-0746, CVE-2009-0747,   CVE-2009-0748, CVE-2009-2847, CVE-2009-2848 to the security issues   fixed in kernel 2.6.18-164.\n\n f. Updated Service Console package python\n\n  Service Console package Python update to version 2.4.3-24.el5.\n\n  When the assert() system call was disabled, an input sanitization   flaw was revealed in the Python string object implementation that   led to a buffer overflow. The missing check for negative size values   meant the Python memory allocator could allocate less memory than   expected. This could result in arbitrary code execution with the   Python interpreter's privileges.\n\n  Multiple buffer and integer overflow flaws were found in the Python   Unicode string processing and in the Python Unicode and string   object implementations. An attacker could use these flaws to cause   a denial of service.\n\n  Multiple integer overflow flaws were found in the Python imageop   module. If a Python application used the imageop module to   process untrusted images, it could cause the application to   disclose sensitive information, crash or, potentially, execute   arbitrary code with the Python interpreter's privileges.\n\n  Multiple integer underflow and overflow flaws were found in the   Python snprintf() wrapper implementation. An attacker could use   these flaws to cause a denial of service (memory corruption).\n\n  Multiple integer overflow flaws were found in various Python   modules. An attacker could use these flaws to cause a denial of   service.\n\n  An integer signedness error, leading to a buffer overflow, was   found in the Python zlib extension module. If a Python application   requested the negative byte count be flushed for a decompression   stream, it could cause the application to crash or, potentially,   execute arbitrary code with the Python interpreter's privileges.\n\n  A flaw was discovered in the strxfrm() function of the Python   locale module. Strings generated by this function were not properly   NULL-terminated, which could possibly cause disclosure of data   stored in the memory of a Python application using this function.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the names CVE-2007-2052 CVE-2007-4965 CVE-2008-1721   CVE-2008-1887 CVE-2008-2315 CVE-2008-3142 CVE-2008-3143   CVE-2008-3144 CVE-2008-4864 CVE-2008-5031 to these issues.\n\n g. Updated Service Console package bind\n\n  Service Console package bind updated to version 9.3.6-4.P1.el5\n\n  The Berkeley Internet Name Domain (BIND) is an implementation of the   Domain Name System (DNS) protocols. BIND includes a DNS server   (named); a resolver library (routines for applications to use when   interfacing with DNS); and tools for verifying that the DNS server   is operating correctly.\n\n  A flaw was found in the way BIND handles dynamic update message   packets containing the 'ANY' record type. A remote attacker could   use this flaw to send a specially crafted dynamic update packet   that could cause named to exit with an assertion failure.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the name CVE-2009-0696 to this issue.\n\n h. Updated Service Console package libxml2\n\n  Service Console package libxml2 updated to version 2.6.26-2.1.2.8.\n\n  libxml is a library for parsing and manipulating XML files. A   Document Type Definition (DTD) defines the legal syntax (and also   which elements can be used) for certain types of files, such as XML   files.\n\n  A stack overflow flaw was found in the way libxml processes the   root XML document element definition in a DTD. A remote attacker   could provide a specially crafted XML file, which once opened by a   local, unsuspecting user, would lead to denial of service.\n\n  Multiple use-after-free flaws were found in the way libxml parses   the Notation and Enumeration attribute types. A remote attacker   could provide a specially crafted XML file, which once opened by a   local, unsuspecting user, would lead to denial of service.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the names CVE-2009-2414 and CVE-2009-2416 to these   issues.\n\n i. Updated Service Console package curl\n\n  Service Console package curl updated to version 7.15.5-2.1.el5_3.5\n\n  A cURL is affected by the previously published 'null prefix attack',   caused by incorrect handling of NULL characters in X.509   certificates. If an attacker is able to get a carefully-crafted   certificate signed by a trusted Certificate Authority, the attacker   could use the certificate during a man-in-the-middle attack and   potentially confuse cURL into accepting it by mistake.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the name CVE-2009-2417 to this issue\n\n j. Updated Service Console package gnutls\n\n  Service Console package gnutil updated to version 1.4.1-3.el5_3.5\n\n  A flaw was discovered in the way GnuTLS handles NULL characters in   certain fields of X.509 certificates. If an attacker is able to get   a carefully-crafted certificate signed by a Certificate Authority   trusted by an application using GnuTLS, the attacker could use the   certificate during a man-in-the-middle attack and potentially   confuse the application into accepting it by mistake.\n\n  The Common Vulnerabilities and Exposures project (cve.mitre.org)   has assigned the name CVE-2009-2730 to this issue",
            "last seen": "2019-02-21",
            "modified": "2018-08-06",
            "plugin id": "42870",
            "published": "2009-11-23",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=42870",
            "title": "VMSA-2009-0016 : VMware vCenter and ESX update release and vMA patch release address multiple security issues in third party components."
        },
        {
            "NASL family": "FreeBSD Local Security Checks",
            "NASL id": "FREEBSD_PKG_0DCCAA287F3C11DD8DE50030843D3802.NASL",
            "description": "Secunia reports :\n\nSome vulnerabilities have been reported in Python, where some have unknown impact and others can potentially be exploited by malicious people to cause a DoS (Denial of Service) or to compromise a vulnerable system.\n\nVarious integer overflow errors exist in core modules e.g.\nstringobject, unicodeobject, bufferobject, longobject, tupleobject, stropmodule, gcmodule, mmapmodule.\n\nAn integer overflow in the hashlib module can lead to an unreliable cryptographic digest results.\n\nInteger overflow errors in the processing of unicode strings can be exploited to cause buffer overflows on 32-bit systems.\n\nAn integer overflow exists in the PyOS_vsnprintf() function on architectures that do not have a 'vsnprintf()' function.\n\nAn integer underflow error in the PyOS_vsnprintf() function when passing zero-length strings can lead to memory corruption.",
            "last seen": "2019-02-21",
            "modified": "2018-11-21",
            "plugin id": "34164",
            "published": "2008-09-11",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=34164",
            "title": "FreeBSD : python -- multiple vulnerabilities (0dccaa28-7f3c-11dd-8de5-0030843d3802)"
        },
        {
            "NASL family": "Slackware Local Security Checks",
            "NASL id": "SLACKWARE_SSA_2008-217-01.NASL",
            "description": "New python packages are available for Slackware 10.1, 10.2, 11.0, 12.0, 12.1, and -current to fix security issues.",
            "last seen": "2019-02-21",
            "modified": "2018-06-27",
            "plugin id": "33824",
            "published": "2008-08-05",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33824",
            "title": "Slackware 10.1 / 10.2 / 11.0 / 12.0 / 12.1 / current : python (SSA:2008-217-01)"
        },
        {
            "NASL family": "CentOS Local Security Checks",
            "NASL id": "CENTOS_RHSA-2009-1176.NASL",
            "description": "Updated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 5.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to disclose sensitive information, crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2007-4965, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nAn integer signedness error, leading to a buffer overflow, was found in the Python zlib extension module. If a Python application requested the negative byte count be flushed for a decompression stream, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges.\n(CVE-2008-1721)\n\nA flaw was discovered in the strxfrm() function of the Python locale module. Strings generated by this function were not properly NULL-terminated, which could possibly cause disclosure of data stored in the memory of a Python application using this function.\n(CVE-2007-2052)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-2315 issue.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-11-10",
            "plugin id": "43771",
            "published": "2010-01-06",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=43771",
            "title": "CentOS 5 : python (CESA-2009:1176)"
        },
        {
            "NASL family": "Mandriva Local Security Checks",
            "NASL id": "MANDRIVA_MDVSA-2008-163.NASL",
            "description": "Multiple integer overflows in the imageop module in Python prior to 2.5.3 allowed context-dependent attackers to cause a denial of service (crash) or possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows (CVE-2008-1679). This was due to an incomplete fix for CVE-2007-4965.\n\nDavid Remahl of Apple Product Security reported several integer overflows in a number of core modules (CVE-2008-2315). He also reported an integer overflow in the hashlib module on Python 2.5 that lead to unreliable cryptographic digest results (CVE-2008-2316).\n\nJustin Ferguson reported multiple buffer overflows in unicode string processing that affected 32bit systems (CVE-2008-3142).\n\nMultiple integer overflows were reported by the Google Security Team that had been fixed in Python 2.5.2 (CVE-2008-3143).\n\nJustin Ferguson reported a number of integer overflows and underflows in the PyOS_vsnprintf() function, as well as an off-by-one error when passing zero-length strings, that led to memory corruption (CVE-2008-3144).\n\nThe updated packages have been patched to correct these issues. As well, Python packages on Mandriva Linux 2007.1 and 2008.0 have been updated to version 2.5.2. Due to slight packaging changes on Mandriva Linux 2007.1, a new package is available (tkinter-apps) that contains binary files (such as /usr/bin/idle) that were previously in the tkinter package.",
            "last seen": "2019-02-21",
            "modified": "2018-07-19",
            "plugin id": "37212",
            "published": "2009-04-23",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=37212",
            "title": "Mandriva Linux Security Advisory : python (MDVSA-2008:163)"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "SUSE_PYTHON-5490.NASL",
            "description": "This update of python fixes several security vulnerabilities.\n(CVE-2008-1679 / CVE-2008-1887 / CVE-2008-3143 / CVE-2008-3142 / CVE-2008-3144 / CVE-2008-2315 / CVE-2008-2316) Note: for SLE10 a non-security bug in mmap was fixed too.",
            "last seen": "2019-02-21",
            "modified": "2016-12-22",
            "plugin id": "33923",
            "published": "2008-08-17",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33923",
            "title": "SuSE 10 Security Update : Python (ZYPP Patch Number 5490)"
        },
        {
            "NASL family": "Oracle Linux Local Security Checks",
            "NASL id": "ORACLELINUX_ELSA-2009-1177.NASL",
            "description": "From Red Hat Security Advisory 2009:1177 :\n\nUpdated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 4.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nAn integer signedness error, leading to a buffer overflow, was found in the Python zlib extension module. If a Python application requested the negative byte count be flushed for a decompression stream, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges.\n(CVE-2008-1721)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-07-18",
            "plugin id": "67897",
            "published": "2013-07-12",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=67897",
            "title": "Oracle Linux 4 : python (ELSA-2009-1177)"
        },
        {
            "NASL family": "Red Hat Local Security Checks",
            "NASL id": "REDHAT-RHSA-2009-1178.NASL",
            "description": "Updated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 3.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-11-27",
            "plugin id": "40402",
            "published": "2009-07-28",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=40402",
            "title": "RHEL 3 : python (RHSA-2009:1178)"
        },
        {
            "NASL family": "CentOS Local Security Checks",
            "NASL id": "CENTOS_RHSA-2009-1178.NASL",
            "description": "Updated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 3.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-11-10",
            "plugin id": "40394",
            "published": "2009-07-28",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=40394",
            "title": "CentOS 3 : python (CESA-2009:1178)"
        },
        {
            "NASL family": "Ubuntu Local Security Checks",
            "NASL id": "UBUNTU_USN-632-1.NASL",
            "description": "It was discovered that there were new integer overflows in the imageop module. If an attacker were able to trick a Python application into processing a specially crafted image, they could execute arbitrary code with user privileges. (CVE-2008-1679)\n\nJustin Ferguson discovered that the zlib module did not correctly handle certain archives. If an attacker were able to trick a Python application into processing a specially crafted archive file, they could execute arbitrary code with user privileges. (CVE-2008-1721)\n\nJustin Ferguson discovered that certain string manipulations in Python could be made to overflow. If an attacker were able to pass a specially crafted string through the PyString_FromStringAndSize function, they could execute arbitrary code with user privileges.\n(CVE-2008-1887)\n\nMultiple integer overflows were discovered in Python's core and modules including hashlib, binascii, pickle, md5, stringobject, unicodeobject, bufferobject, longobject, tupleobject, stropmodule, gcmodule, and mmapmodule. If an attacker were able to exploit these flaws they could execute arbitrary code with user privileges or cause Python applications to crash, leading to a denial of service.\n(CVE-2008-2315, CVE-2008-2316, CVE-2008-3142, CVE-2008-3143, CVE-2008-3144).\n\nNote that Tenable Network Security has extracted the preceding description block directly from the Ubuntu security advisory. Tenable has attempted to automatically clean and format it as much as possible without introducing additional issues.",
            "last seen": "2019-02-21",
            "modified": "2018-11-28",
            "plugin id": "33807",
            "published": "2008-08-04",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33807",
            "title": "Ubuntu 6.06 LTS / 7.04 / 7.10 / 8.04 LTS : python2.4, python2.5 vulnerabilities (USN-632-1)"
        },
        {
            "NASL family": "Gentoo Local Security Checks",
            "NASL id": "GENTOO_GLSA-200807-16.NASL",
            "description": "The remote host is affected by the vulnerability described in GLSA-200807-16 (Python: Multiple vulnerabilities)\n\n    Multiple vulnerabilities were discovered in Python:\n    David Remahl of Apple Product Security reported several integer     overflows in core modules such as stringobject, unicodeobject,     bufferobject, longobject, tupleobject, stropmodule, gcmodule,     mmapmodule (CVE-2008-2315).\n    David Remahl of Apple Product Security also reported an integer     overflow in the hashlib module, leading to unreliable cryptographic     digest results (CVE-2008-2316).\n    Justin Ferguson reported multiple buffer overflows in unicode string     processing that only affect 32bit systems (CVE-2008-3142).\n    The Google Security Team reported multiple integer overflows     (CVE-2008-3143).\n    Justin Ferguson reported multiple integer underflows and overflows in     the PyOS_vsnprintf() function, and an off-by-one error when passing     zero-length strings, leading to memory corruption (CVE-2008-3144).\n  Impact :\n\n    A remote attacker could exploit these vulnerabilities in Python     applications or daemons that pass user-controlled input to vulnerable     functions. Exploitation might lead to the execution of arbitrary code     or a Denial of Service. Vulnerabilities within the hashlib might lead     to weakened cryptographic protection of data integrity or authenticity.\n  Workaround :\n\n    There is no known workaround at this time.",
            "last seen": "2019-02-21",
            "modified": "2018-07-11",
            "plugin id": "33782",
            "published": "2008-08-01",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33782",
            "title": "GLSA-200807-16 : Python: Multiple vulnerabilities"
        },
        {
            "NASL family": "Scientific Linux Local Security Checks",
            "NASL id": "SL_20090728_PYTHON_FOR_SL_3_0_X.NASL",
            "description": "When the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nWould like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.",
            "last seen": "2019-02-21",
            "modified": "2019-01-02",
            "plugin id": "60624",
            "published": "2012-08-01",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=60624",
            "title": "Scientific Linux Security Update : python for SL 3.0.x on i386/x86_64"
        },
        {
            "NASL family": "Red Hat Local Security Checks",
            "NASL id": "REDHAT-RHSA-2009-1176.NASL",
            "description": "Updated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 5.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to disclose sensitive information, crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2007-4965, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nAn integer signedness error, leading to a buffer overflow, was found in the Python zlib extension module. If a Python application requested the negative byte count be flushed for a decompression stream, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges.\n(CVE-2008-1721)\n\nA flaw was discovered in the strxfrm() function of the Python locale module. Strings generated by this function were not properly NULL-terminated, which could possibly cause disclosure of data stored in the memory of a Python application using this function.\n(CVE-2007-2052)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-2315 issue.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-11-27",
            "plugin id": "40400",
            "published": "2009-07-28",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=40400",
            "title": "RHEL 5 : python (RHSA-2009:1176)"
        },
        {
            "NASL family": "Oracle Linux Local Security Checks",
            "NASL id": "ORACLELINUX_ELSA-2009-1176.NASL",
            "description": "From Red Hat Security Advisory 2009:1176 :\n\nUpdated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 5.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to disclose sensitive information, crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2007-4965, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nAn integer signedness error, leading to a buffer overflow, was found in the Python zlib extension module. If a Python application requested the negative byte count be flushed for a decompression stream, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges.\n(CVE-2008-1721)\n\nA flaw was discovered in the strxfrm() function of the Python locale module. Strings generated by this function were not properly NULL-terminated, which could possibly cause disclosure of data stored in the memory of a Python application using this function.\n(CVE-2007-2052)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-2315 issue.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-07-18",
            "plugin id": "67896",
            "published": "2013-07-12",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=67896",
            "title": "Oracle Linux 5 : python (ELSA-2009-1176)"
        },
        {
            "NASL family": "Scientific Linux Local Security Checks",
            "NASL id": "SL_20090727_PYTHON_FOR_SL5_X.NASL",
            "description": "When the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to disclose sensitive information, crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2007-4965, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nAn integer signedness error, leading to a buffer overflow, was found in the Python zlib extension module. If a Python application requested the negative byte count be flushed for a decompression stream, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges.\n(CVE-2008-1721)\n\nA flaw was discovered in the strxfrm() function of the Python locale module. Strings generated by this function were not properly NULL-terminated, which could possibly cause disclosure of data stored in the memory of a Python application using this function.\n(CVE-2007-2052)\n\nWould like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-2315 issue.",
            "last seen": "2019-02-21",
            "modified": "2019-01-02",
            "plugin id": "60622",
            "published": "2012-08-01",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=60622",
            "title": "Scientific Linux Security Update : python for SL5.x i386/x86_64"
        },
        {
            "NASL family": "Red Hat Local Security Checks",
            "NASL id": "REDHAT-RHSA-2009-1177.NASL",
            "description": "Updated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 4.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nAn integer signedness error, leading to a buffer overflow, was found in the Python zlib extension module. If a Python application requested the negative byte count be flushed for a decompression stream, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges.\n(CVE-2008-1721)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-11-27",
            "plugin id": "40401",
            "published": "2009-07-28",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=40401",
            "title": "RHEL 4 : python (RHSA-2009:1177)"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "SUSE_11_0_PYTHON-080801.NASL",
            "description": "This update of python fixes several security vulnerabilities.\n(CVE-2008-1679,CVE-2008-1887, CVE-2008-3143, CVE-2008-3142, CVE-2008-3144, CVE-2008-2315, CVE-2008-2316)",
            "last seen": "2019-02-21",
            "modified": "2016-12-21",
            "plugin id": "40115",
            "published": "2009-07-21",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=40115",
            "title": "openSUSE Security Update : python (python-128)"
        },
        {
            "NASL family": "Oracle Linux Local Security Checks",
            "NASL id": "ORACLELINUX_ELSA-2009-1178.NASL",
            "description": "From Red Hat Security Advisory 2009:1178 :\n\nUpdated python packages that fix multiple security issues are now available for Red Hat Enterprise Linux 3.\n\nThis update has been rated as having moderate security impact by the Red Hat Security Response Team.\n\nPython is an interpreted, interactive, object-oriented programming language.\n\nWhen the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain backported patches to correct these issues.",
            "last seen": "2019-02-21",
            "modified": "2018-07-18",
            "plugin id": "67898",
            "published": "2013-07-12",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=67898",
            "title": "Oracle Linux 3 : python (ELSA-2009-1178)"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "SUSE_PYTHON-5491.NASL",
            "description": "This update of python fixes several security vulnerabilities.\n(CVE-2008-1679,CVE-2008-1887, CVE-2008-3143, CVE-2008-3142, CVE-2008-3144, CVE-2008-2315, CVE-2008-2316)",
            "last seen": "2019-02-21",
            "modified": "2016-12-22",
            "plugin id": "33924",
            "published": "2008-08-17",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=33924",
            "title": "openSUSE 10 Security Update : python (python-5491)"
        },
        {
            "NASL family": "Scientific Linux Local Security Checks",
            "NASL id": "SL_20090728_PYTHON_FOR_SL_4_X.NASL",
            "description": "When the assert() system call was disabled, an input sanitization flaw was revealed in the Python string object implementation that led to a buffer overflow. The missing check for negative size values meant the Python memory allocator could allocate less memory than expected. This could result in arbitrary code execution with the Python interpreter's privileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode string processing and in the Python Unicode and string object implementations. An attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If a Python application used the imageop module to process untrusted images, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges. (CVE-2008-1679, CVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python snprintf() wrapper implementation. An attacker could use these flaws to cause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules.\nAn attacker could use these flaws to cause a denial of service (Python application crash). (CVE-2008-2315, CVE-2008-3143)\n\nAn integer signedness error, leading to a buffer overflow, was found in the Python zlib extension module. If a Python application requested the negative byte count be flushed for a decompression stream, it could cause the application to crash or, potentially, execute arbitrary code with the Python interpreter's privileges.\n(CVE-2008-1721)\n\nWould like to thank David Remahl of the Apple Product Security team for responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.",
            "last seen": "2019-02-21",
            "modified": "2019-01-02",
            "plugin id": "60625",
            "published": "2012-08-01",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=60625",
            "title": "Scientific Linux Security Update : python for SL 4.x on i386/x86_64"
        },
        {
            "NASL family": "SuSE Local Security Checks",
            "NASL id": "SUSE9_12215.NASL",
            "description": "This update of python fixes several security vulnerabilities.\n(CVE-2008-1679 / CVE-2008-1887, CVE-2008-3143, CVE-2008-3142, CVE-2008-3144, CVE-2008-2315, CVE-2008-2316)\n\nNote: for SLE10 a non-security bug in mmap was fixed too.",
            "last seen": "2019-02-21",
            "modified": "2016-12-21",
            "plugin id": "41229",
            "published": "2009-09-24",
            "reporter": "Tenable",
            "source": "https://www.tenable.com/plugins/index.php?view=single&id=41229",
            "title": "SuSE9 Security Update : Python (YOU Patch Number 12215)"
        }
    ],
    "oval": [
        {
            "accepted": "2013-04-29T04:02:36.735-04:00",
            "class": "vulnerability",
            "contributors": [
                {
                    "name": "Aharon Chernin",
                    "organization": "SCAP.com, LLC"
                },
                {
                    "name": "Dragos Prisaca",
                    "organization": "G2, Inc."
                }
            ],
            "definition_extensions": [
                {
                    "comment": "The operating system installed on the system is Red Hat Enterprise Linux 3",
                    "oval": "oval:org.mitre.oval:def:11782"
                },
                {
                    "comment": "CentOS Linux 3.x",
                    "oval": "oval:org.mitre.oval:def:16651"
                },
                {
                    "comment": "The operating system installed on the system is Red Hat Enterprise Linux 4",
                    "oval": "oval:org.mitre.oval:def:11831"
                },
                {
                    "comment": "CentOS Linux 4.x",
                    "oval": "oval:org.mitre.oval:def:16636"
                },
                {
                    "comment": "Oracle Linux 4.x",
                    "oval": "oval:org.mitre.oval:def:15990"
                },
                {
                    "comment": "The operating system installed on the system is Red Hat Enterprise Linux 5",
                    "oval": "oval:org.mitre.oval:def:11414"
                },
                {
                    "comment": "The operating system installed on the system is CentOS Linux 5.x",
                    "oval": "oval:org.mitre.oval:def:15802"
                },
                {
                    "comment": "Oracle Linux 5.x",
                    "oval": "oval:org.mitre.oval:def:15459"
                }
            ],
            "description": "Multiple integer overflows in the PyOS_vsnprintf function in Python/mysnprintf.c in Python 2.5.2 and earlier allow context-dependent attackers to cause a denial of service (memory corruption) or have unspecified other impact via crafted input to string formatting operations.  NOTE: the handling of certain integer values is also affected by related integer underflows and an off-by-one error.",
            "family": "unix",
            "id": "oval:org.mitre.oval:def:10170",
            "status": "accepted",
            "submitted": "2010-07-09T03:56:16-04:00",
            "title": "Multiple integer overflows in the PyOS_vsnprintf function in Python/mysnprintf.c in Python 2.5.2 and earlier allow context-dependent attackers to cause a denial of service (memory corruption) or have unspecified other impact via crafted input to string formatting operations.  NOTE: the handling of certain integer values is also affected by related integer underflows and an off-by-one error.",
            "version": "24"
        },
        {
            "accepted": "2014-01-20T04:01:36.453-05:00",
            "class": "vulnerability",
            "contributors": [
                {
                    "name": "Pai Peng",
                    "organization": "Hewlett-Packard"
                },
                {
                    "name": "Chris Coffin",
                    "organization": "The MITRE Corporation"
                }
            ],
            "definition_extensions": [
                {
                    "comment": "VMWare ESX Server 3.0.3 is installed",
                    "oval": "oval:org.mitre.oval:def:6026"
                },
                {
                    "comment": "VMware ESX Server 3.5.0 is installed",
                    "oval": "oval:org.mitre.oval:def:5887"
                },
                {
                    "comment": "VMware ESX Server 4.0 is installed",
                    "oval": "oval:org.mitre.oval:def:6293"
                }
            ],
            "description": "Multiple integer overflows in the PyOS_vsnprintf function in Python/mysnprintf.c in Python 2.5.2 and earlier allow context-dependent attackers to cause a denial of service (memory corruption) or have unspecified other impact via crafted input to string formatting operations.  NOTE: the handling of certain integer values is also affected by related integer underflows and an off-by-one error.",
            "family": "unix",
            "id": "oval:org.mitre.oval:def:7725",
            "status": "accepted",
            "submitted": "2010-03-19T16:57:59.000-04:00",
            "title": "VMware python multiple integer overflows vulnerability in the PyOS_vsnprintf function",
            "version": "7"
        }
    ],
    "ranking": [
        [
            {
                "circl": 3
            }
        ]
    ],
    "redhat": {
        "rpms": [
            "python-0:2.4.3-24.el5_3.6",
            "python-devel-0:2.4.3-24.el5_3.6",
            "python-tools-0:2.4.3-24.el5_3.6",
            "tkinter-0:2.4.3-24.el5_3.6",
            "python-0:2.3.4-14.7.el4_8.2",
            "python-devel-0:2.3.4-14.7.el4_8.2",
            "python-docs-0:2.3.4-14.7.el4_8.2",
            "python-tools-0:2.3.4-14.7.el4_8.2",
            "tkinter-0:2.3.4-14.7.el4_8.2",
            "python-0:2.2.3-6.11",
            "python-devel-0:2.2.3-6.11",
            "python-tools-0:2.2.3-6.11",
            "tkinter-0:2.2.3-6.11"
        ]
    },
    "references": [
        "http://bugs.gentoo.org/show_bug.cgi?id=232137",
        "http://bugs.python.org/issue2588",
        "http://bugs.python.org/issue2589",
        "http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html",
        "http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html",
        "http://security.gentoo.org/glsa/glsa-200807-16.xml",
        "http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289",
        "http://support.apple.com/kb/HT3438",
        "http://svn.python.org/view?rev=63728&view=rev",
        "http://svn.python.org/view?rev=63734&view=rev",
        "http://svn.python.org/view?rev=63883&view=rev",
        "http://wiki.rpath.com/Advisories:rPSA-2008-0243",
        "http://www.debian.org/security/2008/dsa-1667",
        "http://www.mandriva.com/security/advisories?name=MDVSA-2008:163",
        "http://www.mandriva.com/security/advisories?name=MDVSA-2008:164",
        "http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900",
        "http://www.securityfocus.com/archive/1/495445/100/0/threaded",
        "http://www.securityfocus.com/archive/1/507985/100/0/threaded",
        "http://www.securityfocus.com/bid/30491",
        "http://www.ubuntu.com/usn/usn-632-1",
        "http://www.vmware.com/security/advisories/VMSA-2009-0016.html",
        "http://www.vupen.com/english/advisories/2008/2288",
        "http://www.vupen.com/english/advisories/2009/3316",
        "https://exchange.xforce.ibmcloud.com/vulnerabilities/44171",
        "https://exchange.xforce.ibmcloud.com/vulnerabilities/44173"
    ],
    "refmap": {
        "apple": [
            "APPLE-SA-2009-02-12"
        ],
        "bid": [
            "30491"
        ],
        "bugtraq": [
            "20080813 rPSA-2008-0243-1 idle python",
            "20091120 VMSA-2009-0016 VMware vCenter and ESX update release and vMA patch release address multiple security issue in third party components"
        ],
        "confirm": [
            "http://bugs.gentoo.org/show_bug.cgi?id=232137",
            "http://bugs.python.org/issue2588",
            "http://bugs.python.org/issue2589",
            "http://support.apple.com/kb/HT3438",
            "http://svn.python.org/view?rev=63728&view=rev",
            "http://svn.python.org/view?rev=63734&view=rev",
            "http://svn.python.org/view?rev=63883&view=rev",
            "http://wiki.rpath.com/Advisories:rPSA-2008-0243",
            "http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900",
            "http://www.vmware.com/security/advisories/VMSA-2009-0016.html"
        ],
        "debian": [
            "DSA-1667"
        ],
        "gentoo": [
            "GLSA-200807-16"
        ],
        "mandriva": [
            "MDVSA-2008:163",
            "MDVSA-2008:164"
        ],
        "secunia": [
            "31305",
            "31332",
            "31358",
            "31365",
            "31473",
            "31518",
            "31687",
            "32793",
            "33937",
            "37471"
        ],
        "slackware": [
            "SSA:2008-217-01"
        ],
        "suse": [
            "SUSE-SR:2008:017"
        ],
        "ubuntu": [
            "USN-632-1"
        ],
        "vupen": [
            "ADV-2008-2288",
            "ADV-2009-3316"
        ],
        "xf": [
            "python-multiple-bo(44173)",
            "python-pyosvsnprintf-bo(44171)"
        ]
    },
    "summary": "Multiple integer overflows in the PyOS_vsnprintf function in Python/mysnprintf.c in Python 2.5.2 and earlier allow context-dependent attackers to cause a denial of service (memory corruption) or have unspecified other impact via crafted input to string formatting operations.  NOTE: the handling of certain integer values is also affected by related integer underflows and an off-by-one error.",
    "vulnerable_configuration": [
        {
            "id": "cpe:2.3:a:python_software_foundation:python:1.5.2",
            "title": "cpe:2.3:a:python_software_foundation:python:1.5.2"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:1.6",
            "title": "cpe:2.3:a:python_software_foundation:python:1.6"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:1.6.1",
            "title": "cpe:2.3:a:python_software_foundation:python:1.6.1"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.0",
            "title": "cpe:2.3:a:python_software_foundation:python:2.0"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.0.1",
            "title": "cpe:2.3:a:python_software_foundation:python:2.0.1"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.1",
            "title": "cpe:2.3:a:python_software_foundation:python:2.1"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.1.1",
            "title": "cpe:2.3:a:python_software_foundation:python:2.1.1"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.1.2",
            "title": "cpe:2.3:a:python_software_foundation:python:2.1.2"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.1.3",
            "title": "cpe:2.3:a:python_software_foundation:python:2.1.3"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.2",
            "title": "cpe:2.3:a:python_software_foundation:python:2.2"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.2.1",
            "title": "cpe:2.3:a:python_software_foundation:python:2.2.1"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.2.2",
            "title": "cpe:2.3:a:python_software_foundation:python:2.2.2"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.2.3",
            "title": "cpe:2.3:a:python_software_foundation:python:2.2.3"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.3",
            "title": "cpe:2.3:a:python_software_foundation:python:2.3"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.3.1",
            "title": "cpe:2.3:a:python_software_foundation:python:2.3.1"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.3.2",
            "title": "cpe:2.3:a:python_software_foundation:python:2.3.2"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.3.3",
            "title": "cpe:2.3:a:python_software_foundation:python:2.3.3"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.3.4",
            "title": "cpe:2.3:a:python_software_foundation:python:2.3.4"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.3.5",
            "title": "cpe:2.3:a:python_software_foundation:python:2.3.5"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.3.6",
            "title": "cpe:2.3:a:python_software_foundation:python:2.3.6"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.3.7",
            "title": "cpe:2.3:a:python_software_foundation:python:2.3.7"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.4",
            "title": "cpe:2.3:a:python_software_foundation:python:2.4"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.4.1",
            "title": "cpe:2.3:a:python_software_foundation:python:2.4.1"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.4.2",
            "title": "cpe:2.3:a:python_software_foundation:python:2.4.2"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.4.3",
            "title": "cpe:2.3:a:python_software_foundation:python:2.4.3"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.4.4",
            "title": "cpe:2.3:a:python_software_foundation:python:2.4.4"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.4.5",
            "title": "cpe:2.3:a:python_software_foundation:python:2.4.5"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.5",
            "title": "cpe:2.3:a:python_software_foundation:python:2.5"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.5.1",
            "title": "cpe:2.3:a:python_software_foundation:python:2.5.1"
        },
        {
            "id": "cpe:2.3:a:python_software_foundation:python:2.5.2",
            "title": "cpe:2.3:a:python_software_foundation:python:2.5.2"
        }
    ],
    "vulnerable_configuration_cpe_2_2": [
        "cpe:/a:python_software_foundation:python:1.5.2",
        "cpe:/a:python_software_foundation:python:1.6",
        "cpe:/a:python_software_foundation:python:1.6.1",
        "cpe:/a:python_software_foundation:python:2.0",
        "cpe:/a:python_software_foundation:python:2.0.1",
        "cpe:/a:python_software_foundation:python:2.1",
        "cpe:/a:python_software_foundation:python:2.1.1",
        "cpe:/a:python_software_foundation:python:2.1.2",
        "cpe:/a:python_software_foundation:python:2.1.3",
        "cpe:/a:python_software_foundation:python:2.2",
        "cpe:/a:python_software_foundation:python:2.2.1",
        "cpe:/a:python_software_foundation:python:2.2.2",
        "cpe:/a:python_software_foundation:python:2.2.3",
        "cpe:/a:python_software_foundation:python:2.3",
        "cpe:/a:python_software_foundation:python:2.3.1",
        "cpe:/a:python_software_foundation:python:2.3.2",
        "cpe:/a:python_software_foundation:python:2.3.3",
        "cpe:/a:python_software_foundation:python:2.3.4",
        "cpe:/a:python_software_foundation:python:2.3.5",
        "cpe:/a:python_software_foundation:python:2.3.6",
        "cpe:/a:python_software_foundation:python:2.3.7",
        "cpe:/a:python_software_foundation:python:2.4",
        "cpe:/a:python_software_foundation:python:2.4.1",
        "cpe:/a:python_software_foundation:python:2.4.2",
        "cpe:/a:python_software_foundation:python:2.4.3",
        "cpe:/a:python_software_foundation:python:2.4.4",
        "cpe:/a:python_software_foundation:python:2.4.5",
        "cpe:/a:python_software_foundation:python:2.5",
        "cpe:/a:python_software_foundation:python:2.5.1",
        "cpe:/a:python_software_foundation:python:2.5.2"
    ]
}